#pragma once

#define DEFAULT_SCREEN_WIDTH 1280
#define DEFAULT_SCREEN_HEIGHT 720
#define DINO_APPLICATION_NAME "DiNo"

#define DINO_BACKGROUND_COLOR 0.1, 0.1, 0.1, 1.0

#define MAIN_WINDOW_TITLE "DiNo_MAIN_WINDOW"


#define POPUP_WINDOW_TITLE_BG .2f, .2f, .2f, 1.00f
#define POPUP_WINDOW_TITLE_BG_ACTIVE .2f, .2f, .2f, 1.00f
#define POPUP_WINDOW_TITLE_BG_COLLAPSED .2f, .2f, .2f, 1.00f

#define MINIMUM_INPUT_NODES 1
#define MINIMUM_OUTPUT_NODES 0